apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-webservice
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: customer-webservice
  template:
    metadata:
      labels:
        app: customer-webservice
    spec:
      containers:
      - name: ctr-customer
        image: us-phoenix-1.ocir.io/grpi1rdiczld/customer:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customer-webservice-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-webservice
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-webservice
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001 # Escolha uma porta disponível no intervalo 30000-32767
  type: NodePort  