apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-webservice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: customer-webservice
  template:
    metadata:
      labels:
        app: customer-webservice
    spec:
      containers:
      - name: ctr-customer
        image: localhost:5000/customer-webservice:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
replicas: 2