apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-webservice
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001 # Escolha uma porta disponível no intervalo 30000-32767
  type: NodePort