apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-service
  template:
    metadata:
      labels:
        app: postgresql-service
    spec:
      containers:
      - name: ctr-postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: customers
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: 123456
